package com.praveen.apachecxf.soap.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2019-10-20T03:18:58.256+05:30
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://service.soap.apachecxf.praveen.com/", name = "PaymentProcessor")
@XmlSeeAlso({ObjectFactory.class})
public interface PaymentProcessor {

    @WebMethod
    @RequestWrapper(localName = "processPayment", targetNamespace = "http://service.soap.apachecxf.praveen.com/", className = "com.praveen.apachecxf.soap.service.ProcessPayment")
    @ResponseWrapper(localName = "processPaymentResponse", targetNamespace = "http://service.soap.apachecxf.praveen.com/", className = "com.praveen.apachecxf.soap.service.ProcessPaymentResponse")
    @WebResult(name = "response", targetNamespace = "")
    public com.praveen.apachecxf.soap.service.PaymentProcessorResponse processPayment(
        @WebParam(name = "PaymentProcessorRequest", targetNamespace = "")
        com.praveen.apachecxf.soap.service.PaymentProcessorRequest paymentProcessorRequest
    );
}
